---@diagnostic disable: undefined-global

local rosewater = "#f5e0dc"
local flamingo = "#f2cdcd"
local pink = "#f5c2e7"
local mauve = "#cba6f7"
local red = "#f38ba8"
local maroon = "#eba0ac"
local peach = "#fab387"
local yellow = "#f9e2af"
local green = "#a6e3a1"
local teal = "#94e2d5"
local sky = "#89dceb"
local sapphire = "#74c7ec"
local blue = "#89b4fa"
local lavender = "#b4befe"
local text = "#cdd6f4"
local subtext1 = "#bac2de"
local subtext0 = "#a6adc8"
local overlay2 = "#9399b2"
local overlay1 = "#7f849c"
local overlay0 = "#6c7086"
local surface2 = "#585b70"
local surface1 = "#45475a"
local surface0 = "#313244"
local base = "#1e1e2e"
local mantle = "#181825"
local crust = "#11111b"
local cursorline = "#2a2b3c"
local diff_change_bg = "#25293c"
local diagnostic_info_bg = "#283040"
local diagnostic_hint_bg = "#29313e"
local diagnostic_error_bg = "#32283a"
local diagnostic_warn_bg = "#33313a"
local diff_add_bg = "#364143"
local selection_match_bg = "#393b4d"
local diff_text_bg = "#3e4b6b"
local search_bg = "#3e5767"
local diff_delete_bg = "#443244"
local inc_search_bg = "#7ec9d8"

vim.cmd.highlight("clear")
vim.cmd.syntax("reset")

vim.g.colors_name = "catppuccin-mocha"

-- Terminal colours
vim.g.terminal_color_0 = overlay0
vim.g.terminal_color_1 = red
vim.g.terminal_color_2 = green
vim.g.terminal_color_3 = yellow
vim.g.terminal_color_4 = blue
vim.g.terminal_color_5 = pink
vim.g.terminal_color_6 = teal
vim.g.terminal_color_7 = subtext0
vim.g.terminal_color_8 = surface2
vim.g.terminal_color_9 = red
vim.g.terminal_color_10 = green
vim.g.terminal_color_11 = yellow
vim.g.terminal_color_12 = blue
vim.g.terminal_color_13 = pink
vim.g.terminal_color_14 = teal
vim.g.terminal_color_15 = subtext1

-- Editor UI
vim.api.nvim_set_hl(0, "Bold", { bold = true })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = surface0 })
vim.api.nvim_set_hl(0, "ComplHint", { fg = subtext0 })
vim.api.nvim_set_hl(0, "ComplHintMore", { link = "Question" })
vim.api.nvim_set_hl(0, "ComplMatchIns", { link = "PreInsert" })
vim.api.nvim_set_hl(0, "Conceal", { fg = overlay1 })
vim.api.nvim_set_hl(0, "CurSearch", { fg = mantle, bg = red })
vim.api.nvim_set_hl(0, "Cursor", { fg = base, bg = rosewater })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = cursorline })
vim.api.nvim_set_hl(0, "CursorIM", { fg = base, bg = rosewater })
vim.api.nvim_set_hl(0, "CursorLine", { bg = cursorline })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = lavender })
vim.api.nvim_set_hl(0, "Dimmed", { fg = overlay1 })
vim.api.nvim_set_hl(0, "Directory", { fg = blue })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = surface1 })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = red, bold = true })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = blue, bg = surface0 })
vim.api.nvim_set_hl(0, "FloatShadow", { bg = overlay0, blend = 80 })
vim.api.nvim_set_hl(0, "FloatShadowThrough", { bg = overlay0, blend = 100 })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = subtext0, bg = surface0 })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = overlay0 })
vim.api.nvim_set_hl(0, "Folded", { fg = blue, bg = surface1 })
vim.api.nvim_set_hl(0, "IncSearch", { fg = mantle, bg = inc_search_bg })
vim.api.nvim_set_hl(0, "LineNr", { fg = surface1 })
vim.api.nvim_set_hl(0, "MatchParen", { fg = peach, bg = selection_match_bg, bold = true })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = text, bold = true })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = blue })
vim.api.nvim_set_hl(0, "MsgSeparator", { link = "WinSeparator" })
vim.api.nvim_set_hl(0, "NonText", { fg = overlay0 })
vim.api.nvim_set_hl(0, "Normal", { fg = text, bg = base })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = text, bg = surface0 })
vim.api.nvim_set_hl(0, "NormalNC", { fg = text, bg = base })
vim.api.nvim_set_hl(0, "NormalSB", { fg = text, bg = crust })
vim.api.nvim_set_hl(0, "OkMsg", { fg = green })
vim.api.nvim_set_hl(0, "Pmenu", { fg = text, bg = surface0 })
vim.api.nvim_set_hl(0, "PmenuBorder", { fg = blue, bg = surface0 })
vim.api.nvim_set_hl(0, "PmenuExtra", { fg = text })
vim.api.nvim_set_hl(0, "PmenuExtraSel", { fg = text, bg = surface0, bold = true })
vim.api.nvim_set_hl(0, "PmenuMatch", { fg = text, bold = true })
vim.api.nvim_set_hl(0, "PmenuMatchSel", { bold = true })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = surface0 })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = text, bg = surface1, bold = true })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = overlay0 })
vim.api.nvim_set_hl(0, "PreInsert", { fg = overlay2 })
vim.api.nvim_set_hl(0, "Question", { fg = blue })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = selection_match_bg, bold = true })
vim.api.nvim_set_hl(0, "Search", { fg = text, bg = search_bg })
vim.api.nvim_set_hl(0, "SignColumn", { fg = surface1 })
vim.api.nvim_set_hl(0, "SignColumnSB", { fg = surface1, bg = crust })
vim.api.nvim_set_hl(0, "SpecialKey", { link = "NonText" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = subtext1, bg = mantle })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = surface2, bg = mantle })
vim.api.nvim_set_hl(0, "Substitute", { fg = pink, bg = surface1 })
vim.api.nvim_set_hl(0, "TabLine", { fg = overlay0, bg = crust })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = mantle })
vim.api.nvim_set_hl(0, "TabLineSel", { link = "Normal" })
vim.api.nvim_set_hl(0, "TermCursor", { fg = base, bg = rosewater })
vim.api.nvim_set_hl(0, "TermCursorNC", { fg = base, bg = overlay2 })
vim.api.nvim_set_hl(0, "Title", { fg = blue, bold = true })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "Visual", { bg = surface1 })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = surface1 })
vim.api.nvim_set_hl(0, "VertSplit", { fg = crust })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = yellow })
vim.api.nvim_set_hl(0, "Whitespace", { fg = surface1 })
vim.api.nvim_set_hl(0, "WildMenu", { fg = text, bg = overlay0 })
vim.api.nvim_set_hl(0, "WinBar", { fg = rosewater })
vim.api.nvim_set_hl(0, "WinBarNC", { link = "WinBar" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = crust })
vim.api.nvim_set_hl(0, "lCursor", { fg = base, bg = rosewater })

-- Spell
vim.api.nvim_set_hl(0, "SpellBad", { sp = red, undercurl = true })
vim.api.nvim_set_hl(0, "SpellCap", { sp = yellow, undercurl = true })
vim.api.nvim_set_hl(0, "SpellLocal", { sp = blue, undercurl = true })
vim.api.nvim_set_hl(0, "SpellRare", { sp = green, undercurl = true })

-- Diff
vim.api.nvim_set_hl(0, "Added", { fg = green })
vim.api.nvim_set_hl(0, "Changed", { fg = blue })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = diff_add_bg })
vim.api.nvim_set_hl(0, "DiffChange", { bg = diff_change_bg })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = diff_delete_bg })
vim.api.nvim_set_hl(0, "DiffText", { bg = diff_text_bg })
vim.api.nvim_set_hl(0, "diffAdded", { fg = green })
vim.api.nvim_set_hl(0, "diffChanged", { fg = blue })
vim.api.nvim_set_hl(0, "diffFile", { fg = blue })
vim.api.nvim_set_hl(0, "diffIndexLine", { fg = teal })
vim.api.nvim_set_hl(0, "diffLine", { fg = overlay0 })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = peach })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = yellow })
vim.api.nvim_set_hl(0, "diffRemoved", { fg = red })

-- Syntax (legacy groups)
vim.api.nvim_set_hl(0, "Boolean", { fg = peach })
vim.api.nvim_set_hl(0, "Character", { fg = teal })
vim.api.nvim_set_hl(0, "Comment", { fg = overlay2, italic = true })
vim.api.nvim_set_hl(0, "Conditional", { fg = mauve })
vim.api.nvim_set_hl(0, "Constant", { fg = peach })
vim.api.nvim_set_hl(0, "Debug", { link = "Special" })
vim.api.nvim_set_hl(0, "Define", { link = "PreProc" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = overlay2 })
vim.api.nvim_set_hl(0, "Error", { fg = red })
vim.api.nvim_set_hl(0, "Exception", { fg = mauve })
vim.api.nvim_set_hl(0, "Float", { link = "Number" })
vim.api.nvim_set_hl(0, "Function", { fg = blue })
vim.api.nvim_set_hl(0, "GlyphPalette1", { fg = red })
vim.api.nvim_set_hl(0, "GlyphPalette2", { fg = teal })
vim.api.nvim_set_hl(0, "GlyphPalette3", { fg = yellow })
vim.api.nvim_set_hl(0, "GlyphPalette4", { fg = blue })
vim.api.nvim_set_hl(0, "GlyphPalette6", { fg = teal })
vim.api.nvim_set_hl(0, "GlyphPalette7", { fg = text })
vim.api.nvim_set_hl(0, "GlyphPalette9", { fg = red })
vim.api.nvim_set_hl(0, "Identifier", { fg = flamingo })
vim.api.nvim_set_hl(0, "Include", { fg = mauve })
vim.api.nvim_set_hl(0, "Italic", { italic = true })
vim.api.nvim_set_hl(0, "Keyword", { fg = mauve })
vim.api.nvim_set_hl(0, "Label", { fg = sapphire })
vim.api.nvim_set_hl(0, "Macro", { fg = rosewater })
vim.api.nvim_set_hl(0, "Number", { fg = peach })
vim.api.nvim_set_hl(0, "Operator", { fg = sky })
vim.api.nvim_set_hl(0, "PreCondit", { link = "PreProc" })
vim.api.nvim_set_hl(0, "PreProc", { fg = mauve })
vim.api.nvim_set_hl(0, "Repeat", { fg = mauve })
vim.api.nvim_set_hl(0, "Special", { fg = blue })
vim.api.nvim_set_hl(0, "SpecialChar", { link = "Special" })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Special" })
vim.api.nvim_set_hl(0, "Statement", { fg = mauve })
vim.api.nvim_set_hl(0, "StorageClass", { fg = yellow })
vim.api.nvim_set_hl(0, "String", { fg = green })
vim.api.nvim_set_hl(0, "Structure", { fg = yellow })
vim.api.nvim_set_hl(0, "Tag", { fg = blue })
vim.api.nvim_set_hl(0, "Todo", { fg = base, bg = flamingo, bold = true })
vim.api.nvim_set_hl(0, "Type", { fg = yellow })
vim.api.nvim_set_hl(0, "Typedef", { link = "Type" })
vim.api.nvim_set_hl(0, "csvCol0", { fg = red })
vim.api.nvim_set_hl(0, "csvCol1", { fg = peach })
vim.api.nvim_set_hl(0, "csvCol2", { fg = yellow })
vim.api.nvim_set_hl(0, "csvCol3", { fg = green })
vim.api.nvim_set_hl(0, "csvCol4", { fg = sky })
vim.api.nvim_set_hl(0, "csvCol5", { fg = blue })
vim.api.nvim_set_hl(0, "csvCol6", { fg = lavender })
vim.api.nvim_set_hl(0, "csvCol7", { fg = mauve })
vim.api.nvim_set_hl(0, "csvCol8", { fg = pink })
vim.api.nvim_set_hl(0, "debugBreakpoint", { fg = overlay0, bg = base })
vim.api.nvim_set_hl(0, "debugPC", { bg = crust })
vim.api.nvim_set_hl(0, "healthError", { fg = red })
vim.api.nvim_set_hl(0, "healthSuccess", { fg = teal })
vim.api.nvim_set_hl(0, "healthWarning", { fg = yellow })
vim.api.nvim_set_hl(0, "htmlH1", { fg = pink, bold = true })
vim.api.nvim_set_hl(0, "htmlH2", { fg = blue, bold = true })
vim.api.nvim_set_hl(0, "illuminatedCurWord", { bg = surface1 })
vim.api.nvim_set_hl(0, "illuminatedWord", { bg = surface1 })
vim.api.nvim_set_hl(0, "markdownCode", { fg = green })
vim.api.nvim_set_hl(0, "markdownCodeBlock", { fg = green })
vim.api.nvim_set_hl(0, "markdownH1", { link = "rainbow1" })
vim.api.nvim_set_hl(0, "markdownH2", { link = "rainbow2" })
vim.api.nvim_set_hl(0, "markdownH3", { link = "rainbow3" })
vim.api.nvim_set_hl(0, "markdownH4", { link = "rainbow4" })
vim.api.nvim_set_hl(0, "markdownH5", { link = "rainbow5" })
vim.api.nvim_set_hl(0, "markdownH6", { link = "rainbow6" })
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", { fg = blue })
vim.api.nvim_set_hl(0, "markdownLinkText", { fg = lavender, underline = true })
vim.api.nvim_set_hl(0, "mkdCodeDelimiter", { fg = text, bg = base })
vim.api.nvim_set_hl(0, "mkdCodeEnd", { fg = green, bold = true })
vim.api.nvim_set_hl(0, "mkdCodeStart", { fg = green, bold = true })
vim.api.nvim_set_hl(0, "qfFileName", { fg = blue })
vim.api.nvim_set_hl(0, "qfLineNr", { fg = yellow })
vim.api.nvim_set_hl(0, "rainbow1", { fg = red })
vim.api.nvim_set_hl(0, "rainbow2", { fg = peach })
vim.api.nvim_set_hl(0, "rainbow3", { fg = yellow })
vim.api.nvim_set_hl(0, "rainbow4", { fg = green })
vim.api.nvim_set_hl(0, "rainbow5", { fg = sapphire })
vim.api.nvim_set_hl(0, "rainbow6", { fg = lavender })

-- Tree-sitter
vim.api.nvim_set_hl(0, "@attribute", { fg = yellow })
vim.api.nvim_set_hl(0, "@attribute.c_sharp", { fg = yellow })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@character", { link = "Character" })
vim.api.nvim_set_hl(0, "@character.special", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "@character.special.html", { fg = red })
vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@comment.documentation", { link = "Comment" })
vim.api.nvim_set_hl(0, "@comment.error", { fg = base, bg = red })
vim.api.nvim_set_hl(0, "@comment.hint", { fg = base, bg = blue })
vim.api.nvim_set_hl(0, "@comment.note", { fg = base, bg = blue })
vim.api.nvim_set_hl(0, "@comment.todo", { fg = base, bg = flamingo })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = base, bg = yellow })
vim.api.nvim_set_hl(0, "@comment.warning.gitcommit", { fg = yellow })
vim.api.nvim_set_hl(0, "@conditional", { link = "Conditional" })
vim.api.nvim_set_hl(0, "@constant", { link = "Constant" })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = peach })
vim.api.nvim_set_hl(0, "@constant.java", { fg = teal })
vim.api.nvim_set_hl(0, "@constant.macro", { link = "Macro" })
vim.api.nvim_set_hl(0, "@constructor", { fg = sapphire })
vim.api.nvim_set_hl(0, "@constructor.lua", { link = "@punctuation.bracket" })
vim.api.nvim_set_hl(0, "@constructor.python", { fg = sky })
vim.api.nvim_set_hl(0, "@define", { link = "Define" })
vim.api.nvim_set_hl(0, "@diff.delta", { link = "diffChanged" })
vim.api.nvim_set_hl(0, "@diff.minus", { link = "diffRemoved" })
vim.api.nvim_set_hl(0, "@diff.plus", { link = "diffAdded" })
vim.api.nvim_set_hl(0, "@error", { link = "Error" })
vim.api.nvim_set_hl(0, "@exception", { link = "Exception" })
vim.api.nvim_set_hl(0, "@field", { fg = blue })
vim.api.nvim_set_hl(0, "@float", { link = "Float" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = blue })
vim.api.nvim_set_hl(0, "@function.builtin.bash", { fg = red })
vim.api.nvim_set_hl(0, "@function.call", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.macro", { fg = rosewater })
vim.api.nvim_set_hl(0, "@function.method", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.method.call", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.method.call.php", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.method.php", { link = "Function" })
vim.api.nvim_set_hl(0, "@include", { link = "Include" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { link = "Conditional" })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { link = "Operator" })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.debug", { link = "Exception" })
vim.api.nvim_set_hl(0, "@keyword.directive", { fg = mauve })
vim.api.nvim_set_hl(0, "@keyword.directive.css", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { link = "Define" })
vim.api.nvim_set_hl(0, "@keyword.exception", { link = "Exception" })
vim.api.nvim_set_hl(0, "@keyword.export", { fg = mauve })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = mauve })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "Include" })
vim.api.nvim_set_hl(0, "@keyword.import.c", { fg = yellow })
vim.api.nvim_set_hl(0, "@keyword.import.cpp", { fg = yellow })
vim.api.nvim_set_hl(0, "@keyword.modifier", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = mauve })
vim.api.nvim_set_hl(0, "@keyword.repeat", { link = "Repeat" })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = mauve })
vim.api.nvim_set_hl(0, "@keyword.storage", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.type", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@label", { link = "Label" })
vim.api.nvim_set_hl(0, "@label.yaml", { fg = yellow })
vim.api.nvim_set_hl(0, "@markup", { fg = text })
vim.api.nvim_set_hl(0, "@markup.environment", { fg = pink })
vim.api.nvim_set_hl(0, "@markup.environment.name", { fg = blue })
vim.api.nvim_set_hl(0, "@markup.heading", { fg = yellow })
vim.api.nvim_set_hl(0, "@markup.heading.1.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", { link = "rainbow1" })
vim.api.nvim_set_hl(0, "@markup.heading.2.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", { link = "rainbow2" })
vim.api.nvim_set_hl(0, "@markup.heading.3.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", { link = "rainbow3" })
vim.api.nvim_set_hl(0, "@markup.heading.4.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", { link = "rainbow4" })
vim.api.nvim_set_hl(0, "@markup.heading.5.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", { link = "rainbow5" })
vim.api.nvim_set_hl(0, "@markup.heading.6.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", { link = "rainbow6" })
vim.api.nvim_set_hl(0, "@markup.heading.html", { link = "@markup" })
vim.api.nvim_set_hl(0, "@markup.heading.markdown", {})
vim.api.nvim_set_hl(0, "@markup.italic", { fg = red, italic = true })
vim.api.nvim_set_hl(0, "@markup.link", { fg = blue })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = sapphire })
vim.api.nvim_set_hl(0, "@markup.link.label.html", { fg = text })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = blue, underline = true })
vim.api.nvim_set_hl(0, "@markup.list", { fg = teal })
vim.api.nvim_set_hl(0, "@markup.list.checked", { fg = green })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { fg = overlay2 })
vim.api.nvim_set_hl(0, "@markup.math", { fg = blue })
vim.api.nvim_set_hl(0, "@markup.quote", { fg = pink, italic = true })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = green })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
vim.api.nvim_set_hl(0, "@markup.strong", { fg = red, bold = true })
vim.api.nvim_set_hl(0, "@markup.underline", { link = "Underlined" })
vim.api.nvim_set_hl(0, "@method", { link = "Function" })
vim.api.nvim_set_hl(0, "@method.call", { link = "Function" })
vim.api.nvim_set_hl(0, "@method.call.php", { link = "Function" })
vim.api.nvim_set_hl(0, "@method.php", { link = "Function" })
vim.api.nvim_set_hl(0, "@module", { fg = yellow })
vim.api.nvim_set_hl(0, "@namespace", { fg = yellow })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@number.css", { fg = peach })
vim.api.nvim_set_hl(0, "@number.float", { link = "Float" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.api.nvim_set_hl(0, "@parameter", { fg = maroon })
vim.api.nvim_set_hl(0, "@preproc", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@property", { fg = blue })
vim.api.nvim_set_hl(0, "@property.class.css", { fg = yellow })
vim.api.nvim_set_hl(0, "@property.css", { fg = blue })
vim.api.nvim_set_hl(0, "@property.id.css", { fg = yellow })
vim.api.nvim_set_hl(0, "@property.scss", { fg = blue })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = overlay2 })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter.regex", { link = "@string.regexp" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = sky })
vim.api.nvim_set_hl(0, "@repeat", { link = "Repeat" })
vim.api.nvim_set_hl(0, "@storageclass", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@string.documentation", { fg = teal })
vim.api.nvim_set_hl(0, "@string.escape", { fg = pink })
vim.api.nvim_set_hl(0, "@string.plain.css", { fg = text })
vim.api.nvim_set_hl(0, "@string.regex", { fg = pink })
vim.api.nvim_set_hl(0, "@string.regexp", { fg = pink })
vim.api.nvim_set_hl(0, "@string.special", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.special.path", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.special.path.gitignore", { fg = text })
vim.api.nvim_set_hl(0, "@string.special.symbol", { fg = red })
vim.api.nvim_set_hl(0, "@string.special.symbol.ruby", { fg = red })
vim.api.nvim_set_hl(0, "@string.special.url", { fg = blue, underline = true })
vim.api.nvim_set_hl(0, "@string.special.url.html", { fg = green })
vim.api.nvim_set_hl(0, "@symbol", { fg = flamingo })
vim.api.nvim_set_hl(0, "@symbol.ruby", { fg = flamingo })
vim.api.nvim_set_hl(0, "@tag", { fg = blue })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = yellow })
vim.api.nvim_set_hl(0, "@tag.builtin", { fg = blue })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = teal })
vim.api.nvim_set_hl(0, "@text", { fg = text })
vim.api.nvim_set_hl(0, "@text.danger", { fg = base, bg = red })
vim.api.nvim_set_hl(0, "@text.diff.add", { link = "diffAdded" })
vim.api.nvim_set_hl(0, "@text.diff.delete", { link = "diffRemoved" })
vim.api.nvim_set_hl(0, "@text.emphasis", { fg = red, italic = true })
vim.api.nvim_set_hl(0, "@text.environment", { fg = pink })
vim.api.nvim_set_hl(0, "@text.environment.name", { fg = blue })
vim.api.nvim_set_hl(0, "@text.literal", { fg = green })
vim.api.nvim_set_hl(0, "@text.math", { fg = blue })
vim.api.nvim_set_hl(0, "@text.note", { fg = base, bg = blue })
vim.api.nvim_set_hl(0, "@text.reference", { fg = lavender })
vim.api.nvim_set_hl(0, "@text.strike", { strikethrough = true })
vim.api.nvim_set_hl(0, "@text.strong", { fg = red, bold = true })
vim.api.nvim_set_hl(0, "@text.title", { fg = yellow })
vim.api.nvim_set_hl(0, "@text.title.1.markdown", { link = "rainbow1" })
vim.api.nvim_set_hl(0, "@text.title.2.markdown", { link = "rainbow2" })
vim.api.nvim_set_hl(0, "@text.title.3.markdown", { link = "rainbow3" })
vim.api.nvim_set_hl(0, "@text.title.4.markdown", { link = "rainbow4" })
vim.api.nvim_set_hl(0, "@text.title.5.markdown", { link = "rainbow5" })
vim.api.nvim_set_hl(0, "@text.title.6.markdown", { link = "rainbow6" })
vim.api.nvim_set_hl(0, "@text.todo", { fg = base, bg = flamingo })
vim.api.nvim_set_hl(0, "@text.todo.checked", { fg = green })
vim.api.nvim_set_hl(0, "@text.todo.unchecked", { fg = overlay1 })
vim.api.nvim_set_hl(0, "@text.underline", { link = "Underlined" })
vim.api.nvim_set_hl(0, "@text.warning", { fg = base, bg = yellow })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = mauve })
vim.api.nvim_set_hl(0, "@type.css", { fg = lavender })
vim.api.nvim_set_hl(0, "@type.definition", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.qualifier", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@type.tag.css", { fg = blue })
vim.api.nvim_set_hl(0, "@variable", { fg = text })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = red })
vim.api.nvim_set_hl(0, "@variable.member", { fg = blue })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = maroon })
vim.api.nvim_set_hl(0, "@variable.parameter.bash", { fg = green })
vim.api.nvim_set_hl(0, "gitcommitSummary", { fg = rosewater })
vim.api.nvim_set_hl(0, "zshKSHFunction", { link = "Function" })

-- LSP semantic tokens
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { fg = teal })
vim.api.nvim_set_hl(0, "@lsp.type.variable", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })

-- LSP diagnostics
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = red, bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", { fg = red })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", { fg = teal })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", { fg = sky })
vim.api.nvim_set_hl(0, "DiagnosticFloatingOk", { fg = green })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", { fg = yellow })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = teal, bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = sky, bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = green, bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = red })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = teal })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = sky })
vim.api.nvim_set_hl(0, "DiagnosticSignOk", { fg = green })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = yellow })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = red, undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = teal, undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = sky, undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineOk", { sp = green, undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = yellow, undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = red, bg = diagnostic_error_bg })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = teal, bg = diagnostic_hint_bg })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = sky, bg = diagnostic_info_bg })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextOk", { fg = green, bg = diagnostic_hint_bg })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = yellow, bg = diagnostic_warn_bg })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = yellow, bg = "NONE" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultError", { fg = red })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultHint", { fg = teal })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultInformation", { fg = sky })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultWarning", { fg = yellow })
vim.api.nvim_set_hl(0, "LspDiagnosticsError", { fg = red })
vim.api.nvim_set_hl(0, "LspDiagnosticsHint", { fg = teal })
vim.api.nvim_set_hl(0, "LspDiagnosticsInformation", { fg = sky })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineError", { sp = red, undercurl = true })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineHint", { sp = teal, undercurl = true })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineInformation", { sp = sky, undercurl = true })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineWarning", { sp = yellow, undercurl = true })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextError", { fg = red })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextHint", { fg = teal })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextInformation", { fg = sky })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextWarning", { fg = yellow })
vim.api.nvim_set_hl(0, "LspDiagnosticsWarning", { fg = yellow })

-- LSP references
vim.api.nvim_set_hl(0, "LspCodeLens", { fg = overlay0 })
vim.api.nvim_set_hl(0, "LspCodeLensSeparator", { link = "LspCodeLens" })
vim.api.nvim_set_hl(0, "LspInfoBorder", { link = "FloatBorder" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = surface1, bg = mantle })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = surface1 })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = surface1 })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = surface1 })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = surface0, bold = true })
