[general]
import = ["themes/thalk.toml"]

[font]
size = 16

[font.normal]
family = "JetBrains Mono"
style = "Light"

[font.bold]
style = "Medium"

[mouse]
hide_when_typing = true

[window]
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"
