local base00 = "#151519"
local base01 = "#202024"
local base02 = "#303034"
local base03 = "#505054"
local base04 = "#b0b0b0"
local base05 = "#d0d0d0"
local base06 = "#e0e0e0"
local base07 = "#f5f5f5"
local base08 = "#cc6666"
local base09 = "#de935f"
local base0A = "#f0c674"
local base0B = "#b5bd68"
local base0C = "#8abeb7"
local base0D = "#81a2be"
local base0E = "#b294bb"
local base0F = "#c97b8a"

vim.cmd("highlight clear")
vim.cmd("syntax reset")

vim.g.colors_name = "thalk"

-- Core UI
vim.api.nvim_set_hl(0, "Bold", { bold = true })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = base01 })
vim.api.nvim_set_hl(0, "ComplMatchIns", { fg = base0A, bg = base01, bold = true })
vim.api.nvim_set_hl(0, "Conceal", { fg = base0D, bg = base00 })
vim.api.nvim_set_hl(0, "CurSearch", { fg = base01, bg = base09 })
vim.api.nvim_set_hl(0, "Cursor", { fg = base00, bg = base04 })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = base01 })
vim.api.nvim_set_hl(0, "CursorIM", { fg = base00, bg = base04 })
vim.api.nvim_set_hl(0, "CursorLine", { bg = base01 })
vim.api.nvim_set_hl(0, "CursorLineFold", { bg = base01 })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = base03, bg = base01 })
vim.api.nvim_set_hl(0, "CursorLineSign", { bg = base01 })
vim.api.nvim_set_hl(0, "Debug", { fg = base08 })
vim.api.nvim_set_hl(0, "Directory", { fg = base0D })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = base02 })
vim.api.nvim_set_hl(0, "Error", { fg = base08, bg = base00, bold = true })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = base08 })
vim.api.nvim_set_hl(0, "Exception", { fg = base0E })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = base02, bg = base01 })
vim.api.nvim_set_hl(0, "FloatFooter", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "FloatShadow", { bg = base01 })
vim.api.nvim_set_hl(0, "FloatShadowThrough", { bg = base00 })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = base0D, bg = base01, bold = true })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = base03, bg = base00 })
vim.api.nvim_set_hl(0, "Folded", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "Ignore", { fg = base00 })
vim.api.nvim_set_hl(0, "IncSearch", { fg = base01, bg = base09 })
vim.api.nvim_set_hl(0, "Italic", { italic = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = base03 })
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = base03 })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = base03 })
vim.api.nvim_set_hl(0, "Macro", { fg = base09 })
vim.api.nvim_set_hl(0, "MatchParen", { fg = base09, bg = base01, bold = true })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = base0B })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = base0B })
vim.api.nvim_set_hl(0, "MsgArea", { fg = base05, bg = base00 })
vim.api.nvim_set_hl(0, "MsgSeparator", { fg = base02, bg = base00 })
vim.api.nvim_set_hl(0, "NonText", { fg = base02 })
vim.api.nvim_set_hl(0, "Normal", { fg = base05, bg = base00 })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = base05, bg = base01 })
vim.api.nvim_set_hl(0, "NormalNC", { fg = base05, bg = base00 })
vim.api.nvim_set_hl(0, "Pmenu", { fg = base05, bg = base01 })
vim.api.nvim_set_hl(0, "PmenuExtra", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuExtraSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuKind", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuKindSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuMatch", { fg = base0A, bg = base01, bold = true })
vim.api.nvim_set_hl(0, "PmenuMatchSel", { fg = base0A, bg = base04, bold = true })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = base01 })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = base01, bg = base04, bold = true })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = base02 })
vim.api.nvim_set_hl(0, "Question", { fg = base0D })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = base01 })
vim.api.nvim_set_hl(0, "Search", { fg = base01, bg = base0A })
vim.api.nvim_set_hl(0, "SignColumn", { fg = base03, bg = base00 })
vim.api.nvim_set_hl(0, "StatusLine", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = base03, bg = base01 })
vim.api.nvim_set_hl(0, "StatusLineTerm", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { fg = base03, bg = base01 })
vim.api.nvim_set_hl(0, "Substitute", { fg = base01, bg = base0A })
vim.api.nvim_set_hl(0, "TabLine", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "TabLineFill", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = base04, bg = base00 })
vim.api.nvim_set_hl(0, "TermCursor", { fg = base00, bg = base04 })
vim.api.nvim_set_hl(0, "Title", { fg = base08 })
vim.api.nvim_set_hl(0, "Visual", { bg = base02 })
vim.api.nvim_set_hl(0, "Whitespace", { fg = base02 })
vim.api.nvim_set_hl(0, "WinBar", { fg = base04, bg = base01 })
vim.api.nvim_set_hl(0, "WinBarNC", { fg = base03, bg = base01 })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = base02 })
vim.api.nvim_set_hl(0, "lCursor", { fg = base00, bg = base04 })

-- Diffs
vim.api.nvim_set_hl(0, "DiffAdd", { fg = base0B, bg = base01 })
vim.api.nvim_set_hl(0, "DiffChange", { fg = base0D, bg = base01 })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = base08, bg = base01 })
vim.api.nvim_set_hl(0, "DiffText", { fg = base0D, bg = base01 })

-- Spell checking
vim.api.nvim_set_hl(0, "SpellBad", { undercurl = true, sp = base08 })
vim.api.nvim_set_hl(0, "SpellCap", { undercurl = true, sp = base0A })
vim.api.nvim_set_hl(0, "SpellLocal", { undercurl = true, sp = base0C })
vim.api.nvim_set_hl(0, "SpellRare", { undercurl = true, sp = base0D })

-- Snippets
vim.api.nvim_set_hl(0, "SnippetTabstop", { fg = base0A, bg = base02, bold = true })

-- Legacy syntax (regex based)
vim.api.nvim_set_hl(0, "Boolean", { fg = base09 })
vim.api.nvim_set_hl(0, "Character", { fg = base0C })
vim.api.nvim_set_hl(0, "Comment", { fg = base0F })
vim.api.nvim_set_hl(0, "Conditional", { fg = base0E })
vim.api.nvim_set_hl(0, "Constant", { fg = base09 })
vim.api.nvim_set_hl(0, "Define", { fg = base0E })
vim.api.nvim_set_hl(0, "Delimiter", { fg = base04 })
vim.api.nvim_set_hl(0, "Float", { fg = base09 })
vim.api.nvim_set_hl(0, "Function", { fg = base0D })
vim.api.nvim_set_hl(0, "Identifier", { fg = base05 })
vim.api.nvim_set_hl(0, "Include", { fg = base0E })
vim.api.nvim_set_hl(0, "Keyword", { fg = base0E })
vim.api.nvim_set_hl(0, "Label", { fg = base0C })
vim.api.nvim_set_hl(0, "Number", { fg = base09 })
vim.api.nvim_set_hl(0, "Operator", { fg = base0D })
vim.api.nvim_set_hl(0, "PreCondit", { fg = base0E })
vim.api.nvim_set_hl(0, "PreProc", { fg = base0E })
vim.api.nvim_set_hl(0, "Repeat", { fg = base0E })
vim.api.nvim_set_hl(0, "Special", { fg = base0D })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = base0E })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Comment" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = base03 })
vim.api.nvim_set_hl(0, "Statement", { fg = base0E })
vim.api.nvim_set_hl(0, "StorageClass", { fg = base0A })
vim.api.nvim_set_hl(0, "String", { fg = base0B })
vim.api.nvim_set_hl(0, "Structure", { fg = base0A })
vim.api.nvim_set_hl(0, "Tag", { fg = base0D })
vim.api.nvim_set_hl(0, "Todo", { fg = base0A, bg = base01, bold = true })
vim.api.nvim_set_hl(0, "Type", { fg = base0A })
vim.api.nvim_set_hl(0, "Typedef", { fg = base0A })
vim.api.nvim_set_hl(0, "Underlined", { fg = base0D, underline = true })
vim.api.nvim_set_hl(0, "VertSplit", { fg = base02, bg = base02 })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = base02 })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = base0A })
vim.api.nvim_set_hl(0, "WildMenu", { fg = base01, bg = base04, bold = true })

-- Legacy groups (regex based): Python
vim.api.nvim_set_hl(0, "pythonAttribute", { fg = base0D })
vim.api.nvim_set_hl(0, "pythonExceptions", { fg = base0E })
vim.api.nvim_set_hl(0, "pythonInclude", { fg = base0E })
vim.api.nvim_set_hl(0, "pythonOperator", { fg = base0E })
vim.api.nvim_set_hl(0, "pythonRepeat", { fg = base0E })
vim.api.nvim_set_hl(0, "pythonStatement", { fg = base0E })

-- Legacy groups (regex based): Rust
vim.api.nvim_set_hl(0, "rustEnumVariant", { fg = base0C })
vim.api.nvim_set_hl(0, "rustMacro", { fg = base09 })
vim.api.nvim_set_hl(0, "rustModPath", { fg = base0A })
vim.api.nvim_set_hl(0, "rustSigil", { fg = base0E })
vim.api.nvim_set_hl(0, "rustStorage", { fg = base0E })
vim.api.nvim_set_hl(0, "rustType", { fg = base0E })

-- Diagnostics
vim.api.nvim_set_hl(0, "DiagnosticDeprecated", { strikethrough = true })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = base08 })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", { fg = base08, bg = base01 })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", { fg = base0C, bg = base01 })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", { fg = base0D, bg = base01 })
vim.api.nvim_set_hl(0, "DiagnosticFloatingOk", { fg = base0B, bg = base01 })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", { fg = base0A, bg = base01 })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = base0C })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = base0D })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = base0B })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = base08 })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = base0C })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = base0D })
vim.api.nvim_set_hl(0, "DiagnosticSignOk", { fg = base0B })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = base0A })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = base08 })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = base0C })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = base0D })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineOk", { undercurl = true, sp = base0B })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = base0A })
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", { fg = base03 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualLinesError", { fg = base08 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualLinesHint", { fg = base0C })
vim.api.nvim_set_hl(0, "DiagnosticVirtualLinesInfo", { fg = base0D })
vim.api.nvim_set_hl(0, "DiagnosticVirtualLinesOk", { fg = base0B })
vim.api.nvim_set_hl(0, "DiagnosticVirtualLinesWarn", { fg = base0A })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = base08 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = base0C })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = base0D })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextOk", { fg = base0B })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = base0A })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = base0A })

-- LSP (non-syntax)
vim.api.nvim_set_hl(0, "LspCodeLens", { fg = base03 })
vim.api.nvim_set_hl(0, "LspCodeLensSeparator", { fg = base03 })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = base03, bg = base01 })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = base02 })
vim.api.nvim_set_hl(0, "LspReferenceTarget", { bg = base02 })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = base02 })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = base02 })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = base02, bold = true })

-- Tree-sitter
vim.api.nvim_set_hl(0, "@attribute", { fg = base0A })
vim.api.nvim_set_hl(0, "@attribute.builtin", { fg = base0C })
vim.api.nvim_set_hl(0, "@boolean", { fg = base09 })
vim.api.nvim_set_hl(0, "@character", { fg = base0C })
vim.api.nvim_set_hl(0, "@character.special", { fg = base0E })
vim.api.nvim_set_hl(0, "@comment", { fg = base0F })
vim.api.nvim_set_hl(0, "@comment.documentation", { fg = base0F })
vim.api.nvim_set_hl(0, "@comment.error", { fg = base08, bold = true })
vim.api.nvim_set_hl(0, "@comment.note", { fg = base0D, bold = true })
vim.api.nvim_set_hl(0, "@comment.todo", { fg = base0C, bold = true })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = base0A, bold = true })
vim.api.nvim_set_hl(0, "@constant", { fg = base09 })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = base09 })
vim.api.nvim_set_hl(0, "@constant.macro", { fg = base09 })
vim.api.nvim_set_hl(0, "@constructor", { fg = base0D })
vim.api.nvim_set_hl(0, "@diff.delta", { fg = base0D })
vim.api.nvim_set_hl(0, "@diff.minus", { fg = base08 })
vim.api.nvim_set_hl(0, "@diff.plus", { fg = base0B })
vim.api.nvim_set_hl(0, "@function", { fg = base0D })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = base0D })
vim.api.nvim_set_hl(0, "@function.call", { fg = base0D })
vim.api.nvim_set_hl(0, "@function.macro", { fg = base09 })
vim.api.nvim_set_hl(0, "@function.method", { fg = base0D })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = base0D })
vim.api.nvim_set_hl(0, "@keyword", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { fg = base0D })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.debug", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.directive", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.exception", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.import", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.modifier", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = base0D })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = base0E })
vim.api.nvim_set_hl(0, "@keyword.type", { fg = base0E })
vim.api.nvim_set_hl(0, "@label", { fg = base0C })
vim.api.nvim_set_hl(0, "@markup", { fg = base05 })
vim.api.nvim_set_hl(0, "@markup.heading", { fg = base08 })
vim.api.nvim_set_hl(0, "@markup.heading.1", { fg = base08 })
vim.api.nvim_set_hl(0, "@markup.heading.1.delimiter.vimdoc", { fg = base08 })
vim.api.nvim_set_hl(0, "@markup.heading.2", { fg = base09 })
vim.api.nvim_set_hl(0, "@markup.heading.2.delimiter.vimdoc", { fg = base09 })
vim.api.nvim_set_hl(0, "@markup.heading.3", { fg = base0A })
vim.api.nvim_set_hl(0, "@markup.heading.4", { fg = base0B })
vim.api.nvim_set_hl(0, "@markup.heading.5", { fg = base0D })
vim.api.nvim_set_hl(0, "@markup.heading.6", { fg = base0C })
vim.api.nvim_set_hl(0, "@markup.italic", { italic = true })
vim.api.nvim_set_hl(0, "@markup.link", { fg = base0C })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = base0D })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = base0D, underline = true })
vim.api.nvim_set_hl(0, "@markup.list", { fg = base09 })
vim.api.nvim_set_hl(0, "@markup.list.checked", { fg = base0B })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { fg = base04 })
vim.api.nvim_set_hl(0, "@markup.math", { fg = base0D })
vim.api.nvim_set_hl(0, "@markup.quote", { fg = base04 })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = base04 })
vim.api.nvim_set_hl(0, "@markup.raw.block", { fg = base04 })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
vim.api.nvim_set_hl(0, "@markup.strong", { bold = true })
vim.api.nvim_set_hl(0, "@markup.underline", { underline = true })
vim.api.nvim_set_hl(0, "@module", { fg = base0A })
vim.api.nvim_set_hl(0, "@module.builtin", { fg = base0A })
vim.api.nvim_set_hl(0, "@number", { fg = base09 })
vim.api.nvim_set_hl(0, "@number.float", { fg = base09 })
vim.api.nvim_set_hl(0, "@operator", { fg = base0D })
vim.api.nvim_set_hl(0, "@property", { fg = base0D })
vim.api.nvim_set_hl(0, "@punctuation", { fg = base04 })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = base04 })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = base04 })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = base0D })
vim.api.nvim_set_hl(0, "@string", { fg = base0B })
vim.api.nvim_set_hl(0, "@string.documentation", { fg = base0B })
vim.api.nvim_set_hl(0, "@string.escape", { fg = base0E })
vim.api.nvim_set_hl(0, "@string.regexp", { fg = base0E })
vim.api.nvim_set_hl(0, "@string.special", { fg = base0D })
vim.api.nvim_set_hl(0, "@string.special.path", { fg = base0D })
vim.api.nvim_set_hl(0, "@string.special.symbol", { fg = base08 })
vim.api.nvim_set_hl(0, "@string.special.url", { fg = base0D, underline = true })
vim.api.nvim_set_hl(0, "@tag", { fg = base0D })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = base0A })
vim.api.nvim_set_hl(0, "@tag.builtin", { fg = base0D })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = base04 })
vim.api.nvim_set_hl(0, "@type", { fg = base0A })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = base0E })
vim.api.nvim_set_hl(0, "@type.definition", { fg = base0A })
vim.api.nvim_set_hl(0, "@variable", { fg = base05 })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = base08 })
vim.api.nvim_set_hl(0, "@variable.member", { fg = base0D })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = base05 })
vim.api.nvim_set_hl(0, "@variable.parameter.builtin", { fg = base08 })

-- LSP semantic tokens. These usually link to Tree-sitter groups.
vim.api.nvim_set_hl(0, "@lsp.type.class", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.comment", { link = "@comment" })
vim.api.nvim_set_hl(0, "@lsp.type.decorator", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.enum", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { link = "@constant" })
vim.api.nvim_set_hl(0, "@lsp.type.event", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.function", { link = "@function" })
vim.api.nvim_set_hl(0, "@lsp.type.interface", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.keyword", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@lsp.type.macro", { link = "@function.macro" })
vim.api.nvim_set_hl(0, "@lsp.type.method", { link = "@function.method" })
vim.api.nvim_set_hl(0, "@lsp.type.modifier", { link = "@keyword.modifier" })
vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "@module" })
vim.api.nvim_set_hl(0, "@lsp.type.number", { link = "@number" })
vim.api.nvim_set_hl(0, "@lsp.type.operator", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
vim.api.nvim_set_hl(0, "@lsp.type.regexp", { link = "@string.regexp" })
vim.api.nvim_set_hl(0, "@lsp.type.string", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.type.struct", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.type", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", { link = "@variable.parameter" })
vim.api.nvim_set_hl(0, "@lsp.type.variable", { link = "@variable" })

-- LSP: Rust semantic tokens
vim.api.nvim_set_hl(0, "@lsp.mod.attribute", { italic = true })
vim.api.nvim_set_hl(0, "@lsp.mod.controlFlow", { link = "@keyword.repeat" })
vim.api.nvim_set_hl(0, "@lsp.mod.deprecated", { strikethrough = true })
vim.api.nvim_set_hl(0, "@lsp.mod.intraDocLink.rust", { link = "@markup.link" })
vim.api.nvim_set_hl(0, "@lsp.type.builtinType.rust", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence.rust", { link = "@string.escape" })
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier.rust", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.type.lifetime.rust", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.punctuation.rust", { link = "@punctuation.delimiter" })
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword.rust", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.selfTypeKeyword.rust", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.associated.rust", { link = "@function.method" })
vim.api.nvim_set_hl(0, "@lsp.typemod.generic.injected.rust", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.controlFlow.rust", { link = "@operator" })
