#!/bin/sh

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/plugins

chunkc core::load border.so
chunkc core::load ffm.so
chunkc core::load tiling.so

chunkc set global_desktop_mode bsp
chunkc set global_desktop_offset_bottom 20
chunkc set global_desktop_offset_gap 0
chunkc set global_desktop_offset_left 0
chunkc set global_desktop_offset_right 0
chunkc set global_desktop_offset_top 0

chunkc set desktop_gap_step_size 0
chunkc set desktop_padding_step_size 0

chunkc set window_fade_alpha 0.85
chunkc set window_fade_duration 0.5
chunkc set window_fade_inactive 0
chunkc set window_float_center 1
chunkc set window_float_next 0
chunkc set window_float_topmost 0
chunkc set window_focus_cycle monitor
chunkc set window_region_locked 1

chunkc set focused_border_color 0xff96b5b4
chunkc set focused_border_radius 2
chunkc set focused_border_skip_floating 0
chunkc set focused_border_width 1

chunkc set preselect_border_color 0xffd08770
chunkc set preselect_border_radius 0
chunkc set preselect_border_width 4

chunkc set bsp_optimal_ratio 1.618
chunkc set bsp_spawn_left 1
chunkc set bsp_split_mode optimal
chunkc set bsp_split_ratio 0.5

chunkc set mouse_follows_focus 1
chunkc set mouse_modifier fn

chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile
