[tool.basedpyright]
typeCheckingMode = "recommended"
reportUnusedCallResult = false
reportImplicitStringConcatenation = false

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
  "COM812",
  "D",
  "E501",
  "PTH110",
  "PTH111",
  "PTH118",
  "S603",
  "S607",
  "T201",
]
select = ["ALL"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
