[tool.basedpyright]
pythonVersion = "3.14"
typeCheckingMode = "recommended"
reportImplicitStringConcatenation = false
reportUnusedCallResult = false

[tool.ruff]
target-version = "py314"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = ["COM812", "D203", "D213", "E501", "T201"]
select = ["ALL"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
