---
version: 2
jobs:
  build:
    docker:
      - image: debian:testing-slim
    environment:
      DEBIAN_FRONTEND: noninteractive
      RCRC: /root/project/tag-rcm/rcrc
    steps:
      - run: apt-get update -q
      - run: apt-get install -qq curl git procps python3-pip ruby shellcheck
      - run: >
          curl -s https://apt.thoughtbot.com/thoughtbot.gpg.key | apt-key add -
      - run: >
          echo "deb https://apt.thoughtbot.com/debian/ stable main" >
          /etc/apt/sources.list.d/thoughtbot.list
      - run: apt-get update -q
      - run: apt-get install -qq rcm
      - run: gem install mdl
      - run: pip3 install vim-vint
      - checkout
      - run: grep -lR "#!/bin/sh" tag-* | xargs shellcheck
      - run: mdl .
      - run: vint .
      - run: rcup -d /root/project -v
      - run: lsrc -d /root/project
