#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Scott Stevenson"
email = "scott@stevenson.io"

[ui]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[revsets]
bookmark-advance-to = "@-"

[templates]
draft_commit_description = "builtin_draft_commit_description_with_diff"
git_push_bookmark = '"srs/push-" ++ change_id.short()'
