" ~/.vim/vimrc

call plug#begin()

Plug 'christoomey/vim-sort-motion'
Plug 'conradirwin/vim-bracketed-paste'
Plug 'hynek/vim-python-pep8-indent'
Plug 'jamessan/vim-gnupg'
Plug 'ledger/vim-ledger', { 'for': 'ledger' }
Plug 'scrooloose/syntastic'
Plug 'thoughtbot/pick.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'

call plug#end()

set background=light
set colorcolumn=+1
set diffopt+=vertical
set expandtab
set grepformat=%f:%l:%c:%m
set grepprg=ag\ --vimgrep
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set ruler
set scrolloff=5
set shiftwidth=4
set showmatch
set smartcase
set softtabstop=4
set spelllang=en_gb
set statusline=%<%f\ %h%m%r%y%=%-14.(%l,%c%V%)\ %P
set wildmode=longest:full,list:full

if executable('gpg2')
    let g:GPGExecutable = 'gpg2 --trust-model always'
endif

let g:is_posix = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:tex_flavor = 'latex'

cabbrev <silent> bd lclose\|bdelete
nnoremap <c-p> :call PickFile()<cr>
nnoremap <silent> <c-l> :nohlsearch<cr><c-l>
nnoremap N Nzzzv
nnoremap n nzzzv

function! RemoveTrailingWhitespace()
    let l:view = winsaveview()
    %s/\s\+$//e
    call winrestview(l:view)
endfunction

augroup vimrc
    autocmd!
    autocmd BufWritePre * call RemoveTrailingWhitespace()
    autocmd QuickFixCmdPost *grep* cwindow
augroup END
