" ~/.vim/vimrc

call plug#begin()

Plug 'airblade/vim-gitgutter'
Plug 'chriskempson/base16-vim'
Plug 'christoomey/vim-sort-motion'
    let g:sort_motion_flags = 'u'
Plug 'conradirwin/vim-bracketed-paste'
Plug 'hattya/python-indent.vim'
Plug 'itchyny/lightline.vim'
    let g:lightline = { 'colorscheme': 'jellybeans' }
Plug 'jamessan/vim-gnupg'
Plug 'ledger/vim-ledger'
    let g:ledger_maxwidth = 62
Plug 'scrooloose/syntastic'
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
Plug 'thoughtbot/pick.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'

call plug#end()

let g:is_posix = 1
let g:tex_flavor = 'latex'

set background=dark
set colorcolumn=80
set diffopt+=vertical
set expandtab
set grepformat=%f:%l:%c:%m
set grepprg=ag\ --vimgrep
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set nojoinspaces
set nomodeline
set noshowmode
set number
set relativenumber
set scrolloff=5
set shiftwidth=4
set shortmess+=I
set smartcase
set softtabstop=-1
set spelllang=en_gb
set wildmenu
set wildmode=longest:full,list:full

colorscheme base16-tomorrow

nnoremap <c-p> :call PickFile()<cr>
nnoremap <silent> <c-l> :nohlsearch<cr><c-l>
nnoremap N Nzzzv
nnoremap n nzzzv

function! RemoveTrailingWhitespace()
    let l:view = winsaveview()
    %s/\s\+$//e
    %s/\%^\n\+//e
    %s/\n\+\%$//e
    call winrestview(l:view)
endfunction

augroup vimrc
    autocmd!
    autocmd BufWritePre * call RemoveTrailingWhitespace()
    autocmd QuickFixCmdPost grep cwindow
augroup END
