" ~/.vim/vimrc

call plug#begin()

Plug 'airblade/vim-gitgutter'
Plug 'chriskempson/base16-vim'
Plug 'christoomey/vim-sort-motion'
Plug 'conradirwin/vim-bracketed-paste'
Plug 'felixjung/vim-base16-lightline'
Plug 'hattya/python-indent.vim'
Plug 'itchyny/lightline.vim'
Plug 'ledger/vim-ledger'
Plug 'noahfrederick/vim-neovim-defaults'
Plug 'scrooloose/syntastic'
Plug 'srstevenson/vim-topiary'
Plug 'thoughtbot/pick.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'

call plug#end()

colorscheme base16-tomorrow

set background=dark
set colorcolumn=+1
set diffopt+=vertical
set expandtab
set grepformat=%f:%l:%c:%m
set grepprg=ag\ --vimgrep
set ignorecase
set list
set listchars=tab:→\ ,trail:·,nbsp:+
set nojoinspaces
set nomodeline
set noshowmode
set number
set relativenumber
set scrolloff=5
set shiftround
set shiftwidth=4
set shortmess+=I
set smartcase
set softtabstop=-1
set spelllang=en_gb

let g:is_posix = 1
let g:ledger_maxwidth = 62
let g:lightline = {'colorscheme': 'base16_tomorrow'}
let g:sort_motion_flags = 'u'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:tex_flavor = 'latex'

nnoremap <c-p> :call PickFile()<cr>
nnoremap <silent> <c-l> :nohlsearch<cr><c-l>
nnoremap N Nzzzv
nnoremap n nzzzv

augroup vimrc
    autocmd!
    autocmd QuickFixCmdPost grep cwindow
augroup END
