#!/bin/sh

set -eu

mkdir -p ~/.vim/autoload

plug_dst=~/.vim/autoload/plug.vim
plug_src=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if command -v curl > /dev/null; then
    curl -fLo "$plug_dst" $plug_src
else
    wget -O "$plug_dst" $plug_src
fi

vim -c PlugClean! -c PlugUpdate -c quitall
