#!/usr/bin/env bash

set -euo pipefail

if [[ ! -d "$HOME/.config/nvim/pack/minpac/opt/minpac" ]]; then
    git clone https://github.com/k-takata/minpac.git \
        "$HOME/.config/nvim/pack/minpac/opt/minpac"
fi
