[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

[colors.hints.start]
background = "#f0c674"
foreground = "#151515"

[colors.hints.end]
background = "#b0b0b0"
foreground = "#151515"

[colors.normal]
black = "#151515"
white = "#d0d0d0"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"

[colors.bright]
black = "#505050"
white = "#f5f5f5"
red = "#de935f"
green = "#282a2e"
yellow = "#373b41"
blue = "#b4b7b4"
magenta = "#e0e0e0"
cyan = "#a3685a"
