[colors.primary]
background = "#151515" # base16-classic-dark
foreground = "#d0d0d0" # base16-classic-dark

[colors.normal]
black = "#151515"   # base16-classic-dark
white = "#d0d0d0"   # base16-classic-dark
red = "#cc6666"     # base16-tomorrow-night
green = "#b5bd68"   # base16-tomorrow-night
yellow = "#f0c674"  # base16-tomorrow-night
blue = "#81a2be"    # base16-tomorrow-night
magenta = "#b294bb" # base16-tomorrow-night
cyan = "#8abeb7"    # base16-tomorrow-night

[colors.bright]
black = "#505050"   # base16-classic-dark
white = "#f5f5f5"   # base16-classic-dark
red = "#de935f"     # base16-tomorrow-night
green = "#282a2e"   # base16-tomorrow-night
yellow = "#373b41"  # base16-tomorrow-night
blue = "#b4b7b4"    # base16-tomorrow-night
magenta = "#e0e0e0" # base16-tomorrow-night
cyan = "#a3685a"    # base16-tomorrow-night
