brew "age"
brew "fd"
brew "fish"
brew "fzy"
brew "helix"
brew "jump"
brew "ripgrep"
brew "starship"
brew "tmux"

# Git
brew "gh"
brew "git"
brew "git-delta"

# Programming
brew "bash-language-server"
brew "beancount-language-server"
brew "ltex-ls"
brew "pre-commit"
brew "prettier"
brew "pyright"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "taplo"
brew "uv"

# Typesetting
brew "typst"

# Casks
cask "anki"
cask "brave-browser"
cask "imageoptim"
cask "keymapp"
cask "kitty"
cask "maestral"
cask "signal"
cask "spotify"
cask "standard-notes"
cask "whatsapp"

# Fonts
cask "font-jetbrains-mono"
