brew "bat"
brew "fd"
brew "fish"
brew "fzy"
brew "git"
brew "git-absorb"
brew "helix"
brew "jump"
brew "pre-commit"
brew "ripgrep"
brew "starship"
brew "zellij"

# Beancount
brew "beancount"
brew "beancount-language-server"
brew "fava"

# Markdown
brew "ltex-ls"
brew "mdformat"

# Python
brew "pyright"
brew "ruff"
brew "ruff-lsp"

# Rust
brew "rustup"

# Shell
brew "bash-language-server"
brew "shellcheck"
brew "shfmt"

# TOML
brew "taplo"

# YAML
brew "prettier"

# Casks
cask "1password"
cask "alacritty"
cask "anki"
cask "brave-browser"
cask "rectangle"
cask "signal"
cask "standard-notes"
