[colors]
foreground = "#d0d0d0"
background = "#151515"

selection_fg = "#151515"
selection_bg = "#d0d0d0"

cursor_fg = "#151515"
cursor_bg = "#b0b0b0"
cursor_border = "#b0b0b0"

ansi = [
  "#151515",
  "#cc6666",
  "#b5bd68",
  "#f0c674",
  "#81a2be",
  "#b294bb",
  "#8abeb7",
  "#d0d0d0",
]
brights = [
  "#505050",
  "#cc6666",
  "#b5bd68",
  "#f0c674",
  "#81a2be",
  "#b294bb",
  "#8abeb7",
  "#f5f5f5",
]
