theme = "morandi"

[editor]
bufferline = "multiple"
color-modes = true
line-number = "relative"
rulers = [80]
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"
