theme = "dorrow"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [80]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true
