theme = "tomorrow"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [80]
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
deduplicate-links = false
git-exclude = false
hidden = false

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
tab = "all"
