[language-server]
rumdl = { command = "rumdl", args = ["server"] }

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
language-servers = ["rumdl"]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "toml"
auto-format = true
