"attribute" = "yellow"
"comment" = { fg = "overlay2", modifiers = ["italic"] }
"constant" = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"
"constructor" = "sapphire"
"function" = "blue"
"function.macro" = "rosewater"
"keyword" = "mauve"
"keyword.control.conditional" = "mauve"
"label" = "sapphire"
"namespace" = "yellow"
"operator" = "sky"
"punctuation" = "overlay2"
"punctuation.special" = "sky"
"special" = "blue"
"string" = "green"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"
"tag" = "blue"
"type" = "yellow"
"type.enum.variant" = "teal"
"variable" = "text"
"variable.builtin" = "red"
"variable.other.member" = "blue"
# "variable.parameter" = "maroon"

"markup.bold" = { fg = "red", modifiers = ["bold"] }
"markup.heading.1" = "red"
"markup.heading.2" = "peach"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "sapphire"
"markup.heading.6" = "lavender"
"markup.italic" = { fg = "red", modifiers = ["italic"] }
"markup.link.label" = "sapphire"
"markup.link.text" = "lavender"
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.list" = "teal"
"markup.list.checked" = "green"
"markup.list.unchecked" = "overlay2"
"markup.quote" = "pink"
"markup.raw" = "green"

# "tabstop"

"error" = "red"
"hint" = "teal"
"info" = "sky"
"warning" = "yellow"

"diagnostic" = { underline = { color = "sky", style = "curl" } }
# "diagnostic.deprecated"
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"

"ui.background" = { fg = "text", bg = "mantle" }
# "ui.background.separator"
"ui.bufferline" = { fg = "overlay2", bg = "base" }
"ui.bufferline.active" = { fg = "text", bg = "mantle" }
"ui.bufferline.background" = { bg = "base" }
"ui.cursor" = { fg = "mantle", bg = "secondary_cursor" }
"ui.cursor.insert" = { fg = "mantle", bg = "secondary_cursor_insert" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }
"ui.cursor.normal" = { fg = "mantle", bg = "secondary_cursor_normal" }
"ui.cursor.primary" = { fg = "mantle", bg = "rosewater" }
"ui.cursor.primary.insert" = { fg = "mantle", bg = "green" }
"ui.cursor.primary.normal" = { fg = "mantle", bg = "rosewater" }
"ui.cursor.primary.select" = { fg = "mantle", bg = "lavender" }
"ui.cursor.select" = { fg = "mantle", bg = "secondary_cursor_select" }
# "ui.cursorcolumn.primary"
# "ui.cursorcolumn.secondary"
"ui.cursorline.primary" = { bg = "cursorline" }
# "ui.cursorline.secondary"
# "ui.debug.active"
# "ui.debug.breakpoint"
# "ui.gutter"
# "ui.gutter.selected"
"ui.help" = { fg = "subtext1", bg = "base" }
"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }
# "ui.highlight.frameline"
"ui.linenr" = { fg = "surface1" }
"ui.linenr.selected" = { fg = "overlay2" }
"ui.menu" = { fg = "subtext1", bg = "base" }
# "ui.menu.scroll"
"ui.menu.selected" = { fg = "base", bg = "overlay2", modifiers = ["bold"] }
# "ui.picker.header"
# "ui.picker.header.column"
# "ui.picker.header.column.active"
"ui.popup" = { fg = "text", bg = "base" }
# "ui.popup.info"
"ui.selection" = { bg = "surface1" }
# "ui.selection.primary"
"ui.statusline" = { fg = "subtext1", bg = "base" }
"ui.statusline.inactive" = { fg = "overlay2", bg = "base" }
"ui.statusline.insert" = { fg = "mantle", bg = "green", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "mantle", bg = "rosewater", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "mantle", bg = "lavender", modifiers = [
  "bold",
] }
# "ui.statusline.separator"
"ui.text" = { fg = "text" }
"ui.text.directory" = { fg = "blue" }
"ui.text.focus" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "overlay2", modifiers = ["italic"] }
# "ui.text.info"
# "ui.virtual"
"ui.virtual.indent-guide" = { fg = "surface0" }
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "base" }
# "ui.virtual.inlay-hint.parameter"
# "ui.virtual.inlay-hint.type"
"ui.virtual.jump-label" = { fg = "rosewater", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "base" }
"ui.virtual.whitespace" = { fg = "surface0" }
"ui.virtual.wrap" = { fg = "surface0" }
"ui.window" = { fg = "surface1" }

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
# crust = "#11111b"

cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
secondary_cursor_select = "#878ec0"
secondary_cursor_normal = "#b5a6a8"
secondary_cursor_insert = "#7ea87f"
