"attribute" = { fg = "yellow" }
"comment" = { fg = "overlay2", modifiers = ["italic"] }
"comment.block" = { fg = "overlay2", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "overlay2", modifiers = ["italic"] }
"comment.line" = { fg = "overlay2", modifiers = ["italic"] }
"comment.line.documentation" = { fg = "overlay2", modifiers = ["italic"] }
"constant" = { fg = "peach" }
"constant.builtin" = { fg = "peach" }
"constant.builtin.boolean" = { fg = "peach" }
"constant.character" = { fg = "teal" }
"constant.character.escape" = { fg = "pink" }
"constant.numeric" = { fg = "peach" }
"constant.numeric.float" = { fg = "peach" }
"constant.numeric.integer" = { fg = "peach" }
"constructor" = { fg = "sapphire" }
"function" = { fg = "blue" }
"function.builtin" = { fg = "blue" }
"function.macro" = { fg = "rosewater" }
"function.method" = { fg = "blue" }
"function.special" = { fg = "blue" }
"keyword" = { fg = "mauve" }
"keyword.control" = { fg = "mauve" }
"keyword.control.conditional" = { fg = "mauve" }
"keyword.control.exception" = { fg = "mauve" }
"keyword.control.import" = { fg = "mauve" }
"keyword.control.repeat" = { fg = "mauve" }
"keyword.control.return" = { fg = "mauve" }
"keyword.directive" = { fg = "mauve" }
"keyword.function" = { fg = "mauve" }
"keyword.operator" = { fg = "mauve" }
"keyword.storage" = { fg = "mauve" }
"keyword.storage.modifier" = { fg = "mauve" }
"keyword.storage.type" = { fg = "mauve" }
"label" = { fg = "sapphire" }
"namespace" = { fg = "yellow" }
"operator" = { fg = "sky" }
"punctuation" = { fg = "overlay2" }
"punctuation.bracket" = { fg = "overlay2" }
"punctuation.delimiter" = { fg = "overlay2" }
"punctuation.special" = { fg = "sky" }
"special" = { fg = "blue" }
"string" = { fg = "green" }
"string.regexp" = { fg = "pink" }
"string.special" = { fg = "blue" }
"string.special.path" = { fg = "blue" }
"string.special.symbol" = { fg = "red" }
"string.special.url" = { fg = "blue", underline = { style = "line" } }
"tag" = { fg = "blue" }
"tag.builtin" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "mauve" }
"type.enum.variant" = { fg = "teal" }
"type.parameter" = { fg = "yellow" }
"variable" = { fg = "text" }
"variable.builtin" = { fg = "red" }
"variable.other.member" = { fg = "blue" }
"variable.parameter" = { fg = "maroon" }

"markup.heading" = { fg = "yellow" }
"markup.heading.1" = { fg = "red" }
"markup.heading.2" = { fg = "peach" }
"markup.heading.3" = { fg = "yellow" }
"markup.heading.4" = { fg = "green" }
"markup.heading.5" = { fg = "sapphire" }
"markup.heading.6" = { fg = "lavender" }
"markup.heading.marker" = { fg = "blue" }
"markup.list" = { fg = "teal" }
"markup.list.numbered" = { fg = "teal" }
"markup.list.unchecked" = { fg = "overlay2" }
"markup.list.checked" = { fg = "green" }
"markup.list.unnumbered" = { fg = "teal" }
"markup.bold" = { fg = "red", modifiers = ["bold"] }
"markup.italic" = { fg = "red", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "blue" }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.text" = { fg = "lavender" }
"markup.link.label" = { fg = "sapphire" }
"markup.raw" = { fg = "green" }
"markup.raw.block" = { fg = "green" }
"markup.raw.inline" = { fg = "green" }
"markup.quote" = { fg = "pink", modifiers = ["italic"] }

"diff.plus" = { fg = "green" }
"diff.plus.gutter" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.minus.gutter" = { fg = "red" }
"diff.delta" = { fg = "blue" }
"diff.delta.gutter" = { fg = "blue" }

"diagnostic" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

error = { fg = "red" }
warning = { fg = "yellow" }
info = { fg = "sky" }
hint = { fg = "teal" }

"ui.background" = { fg = "text", bg = "base" }
"ui.background.separator" = { fg = "text", bg = "base" }
"ui.bufferline" = { fg = "subtext0", bg = "mantle" }
"ui.bufferline.active" = { fg = "mauve", bg = "base" }
"ui.bufferline.background" = { bg = "crust" }
"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }
"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.primary" = { fg = "base", bg = "rosewater" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.normal" = { fg = "base", bg = "rosewater" }
"ui.cursor.primary.select" = { fg = "base", bg = "lavender" }
"ui.cursor.select" = { fg = "base", bg = "secondary_cursor_select" }
"ui.cursorcolumn.primary" = { bg = "cursorline" }
"ui.cursorcolumn.secondary" = { bg = "cursorline" }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.cursorline.secondary" = { bg = "cursorline" }
"ui.debug.active" = { fg = "peach" }
"ui.debug.breakpoint" = { fg = "red" }
"ui.gutter" = { bg = "base" }
"ui.gutter.selected" = { bg = "base" }
"ui.help" = { fg = "overlay2", bg = "surface0" }
"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }
"ui.highlight.frameline" = { bg = "surface1", modifiers = ["bold"] }
"ui.linenr" = { fg = "surface1" }
"ui.linenr.selected" = { fg = "lavender" }
"ui.menu" = { fg = "text", bg = "surface0" }
"ui.menu.scroll" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }
"ui.picker.header" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.picker.header.column" = { fg = "text", bg = "surface0" }
"ui.picker.header.column.active" = { fg = "text", bg = "surface1", modifiers = ["bold"] }
"ui.popup" = { fg = "text", bg = "surface0" }
"ui.popup.info" = { fg = "text", bg = "surface0" }
"ui.selection" = { bg = "surface1" }
"ui.selection.primary" = { bg = "surface1" }
"ui.statusline" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.insert" = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "base", bg = "rosewater", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "lavender", modifiers = ["bold"] }
"ui.statusline.separator" = { fg = "subtext1", bg = "mantle" }
"ui.text" = { fg = "text" }
"ui.text.directory" = { fg = "blue" }
"ui.text.focus" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "overlay1" }
"ui.text.info" = { fg = "text" }
"ui.virtual" = { fg = "overlay0" }
"ui.virtual.indent-guide" = { fg = "surface0" }
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "mantle" }
"ui.virtual.inlay-hint.parameter" = { fg = "surface1", bg = "mantle" }
"ui.virtual.inlay-hint.type" = { fg = "surface1", bg = "mantle" }
"ui.virtual.jump-label" = { fg = "rosewater", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "surface0" }
"ui.virtual.whitespace" = { fg = "overlay0" }
"ui.virtual.wrap" = { fg = "overlay0" }
"ui.window" = { fg = "crust" }

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
secondary_cursor_select = "#878ec0"
secondary_cursor_normal = "#b5a6a8"
secondary_cursor_insert = "#7ea87f"
