"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string" = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"

"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }

"ui.background" = { bg = "base00" }
"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base06", bg = "base00" }
"ui.cursor" = { fg = "base09", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "base09", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base09", modifiers = ["reversed"] }
"ui.cursor.select" = { fg = "base09", modifiers = ["reversed"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = "base03"
"ui.linenr.selected" = "base04"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base0D" }
"ui.statusline.select" = { fg = "base00", bg = "base09" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.indent-guide" = "base01"
"ui.virtual.inlay-hint" = "base03"
"ui.virtual.ruler" = { bg = "base01" }
"ui.window" = { bg = "base01" }

[palette]
# base16-classic-dark
base00 = "#151515" # Default Background
base01 = "#202020" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#303030" # Selection Background
base03 = "#505050" # Comments, Invisibles, Line Highlighting
base04 = "#b0b0b0" # Dark Foreground (Used for status bars)
base05 = "#d0d0d0" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e0e0e0" # Light Foreground (Not often used)
base07 = "#f5f5f5" # Light Background (Not often used)

# base16-tomorrow-night
base08 = "#cc6666" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#de935f" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f0c674" # Classes, Markup Bold, Search Text Background
base0B = "#b5bd68" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#8abeb7" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#81a2be" # Functions, Methods, Attribute IDs, Headings
base0E = "#b294bb" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a3685a" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
