inherits = "modus_operandi"

"ui.bufferline" = { fg = "fg-dim", bg = "bg-mode-line-inactive" }
"ui.bufferline.active" = { fg = "fg-main", bg = "bg-main" }
"ui.cursor" = { fg = "bg-main", bg = "bg-active" }
"ui.gutter" = { bg = "bg-main" }
"ui.linenr" = { fg = "bg-active" }
"ui.linenr.selected" = { fg = "fg-alt" }
"ui.statusline" = { fg = "fg-mode-line-active", bg = "bg-mode-line-inactive" }
"ui.statusline.normal" = { fg = "fg-mode-line-active" }
