"attribute" = { fg = "base0A" }
"comment" = { fg = "base04", modifiers = ["italic"] }
"comment.block" = { fg = "base04", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "base04", modifiers = ["italic"] }
"comment.line" = { fg = "base04", modifiers = ["italic"] }
"comment.line.documentation" = { fg = "base04", modifiers = ["italic"] }
"constant" = { fg = "base09" }
"constant.builtin" = { fg = "base09" }
"constant.builtin.boolean" = { fg = "base09" }
"constant.character" = { fg = "base0C" }
"constant.character.escape" = { fg = "base0E" }
"constant.numeric" = { fg = "base09" }
"constant.numeric.float" = { fg = "base09" }
"constant.numeric.integer" = { fg = "base09" }
"constructor" = { fg = "base0D" }
"function" = { fg = "base0D" }
"function.builtin" = { fg = "base0D" }
"function.macro" = { fg = "base09" }
"function.method" = { fg = "base0D" }
"function.special" = { fg = "base0D" }
"keyword" = { fg = "base0E" }
"keyword.control" = { fg = "base0E" }
"keyword.control.conditional" = { fg = "base0E" }
"keyword.control.exception" = { fg = "base0E" }
"keyword.control.import" = { fg = "base0E" }
"keyword.control.repeat" = { fg = "base0E" }
"keyword.control.return" = { fg = "base0E" }
"keyword.directive" = { fg = "base0E" }
"keyword.function" = { fg = "base0E" }
"keyword.operator" = { fg = "base0E" }
"keyword.storage" = { fg = "base0E" }
"keyword.storage.modifier" = { fg = "base0E" }
"keyword.storage.type" = { fg = "base0E" }
"label" = { fg = "base0C" }
"namespace" = { fg = "base0A" }
"operator" = { fg = "base0D" }
"punctuation" = { fg = "base04" }
"punctuation.bracket" = { fg = "base04" }
"punctuation.delimiter" = { fg = "base04" }
"punctuation.special" = { fg = "base0D" }
"special" = { fg = "base0D" }
"string" = { fg = "base0B" }
"string.regexp" = { fg = "base0E" }
"string.special" = { fg = "base0D" }
"string.special.path" = { fg = "base0D" }
"string.special.symbol" = { fg = "base08" }
"string.special.url" = { fg = "base0D", underline = { style = "line" } }
"tag" = { fg = "base0D" }
"tag.builtin" = { fg = "base0D" }
"type" = { fg = "base0A" }
"type.builtin" = { fg = "base0E" }
"type.enum.variant" = { fg = "base0C" }
"type.parameter" = { fg = "base0A" }
"variable" = { fg = "base05" }
"variable.builtin" = { fg = "base08" }
"variable.other.member" = { fg = "base0D" }
"variable.parameter" = { fg = "base05" }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading.1" = { fg = "base08", modifiers = ["bold"] }
"markup.heading.2" = { fg = "base09", modifiers = ["bold"] }
"markup.heading.3" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading.4" = { fg = "base0B", modifiers = ["bold"] }
"markup.heading.5" = { fg = "base0D", modifiers = ["bold"] }
"markup.heading.6" = { fg = "base0C", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "base0D" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "base0D" }
"markup.link.label" = { fg = "base0D" }
"markup.link.text" = { fg = "base0C" }
"markup.link.url" = { fg = "base0D", underline = { style = "line" } }
"markup.list" = { fg = "base09" }
"markup.list.checked" = { fg = "base0B" }
"markup.list.numbered" = { fg = "base09" }
"markup.list.unchecked" = { fg = "base04" }
"markup.list.unnumbered" = { fg = "base09" }
"markup.quote" = { fg = "base04", modifiers = ["italic"] }
"markup.raw" = { fg = "base04" }
"markup.raw.block" = { fg = "base04" }
"markup.raw.inline" = { fg = "base04" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = { fg = "base0D" }
"diff.delta.gutter" = { fg = "base0D" }
"diff.minus" = { fg = "base08" }
"diff.minus.gutter" = { fg = "base08" }
"diff.plus" = { fg = "base0B" }
"diff.plus.gutter" = { fg = "base0B" }

"diagnostic" = { underline = { color = "base0D", style = "curl" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "base08", style = "curl" } }
"diagnostic.hint" = { underline = { color = "base0C", style = "curl" } }
"diagnostic.info" = { underline = { color = "base0D", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "base0A", style = "curl" } }

"error" = { fg = "base08" }
"hint" = { fg = "base0C" }
"info" = { fg = "base0D" }
"warning" = { fg = "base0A" }

"ui.background" = { bg = "base00" }
"ui.background.separator" = { fg = "base00" }
"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base06", bg = "base00" }
"ui.bufferline.background" = { bg = "base01" }
"ui.cursor" = { fg = "base00", bg = "base04" }
"ui.cursor.insert" = { fg = "base00", bg = "base04" }
"ui.cursor.match" = { fg = "base09", modifiers = ["bold"] }
"ui.cursor.normal" = { fg = "base00", bg = "base04" }
"ui.cursor.primary" = { fg = "base00", bg = "base05" }
"ui.cursor.primary.insert" = { fg = "base00", bg = "base05" }
"ui.cursor.primary.normal" = { fg = "base00", bg = "base05" }
"ui.cursor.primary.select" = { fg = "base00", bg = "base05" }
"ui.cursor.select" = { fg = "base01", bg = "base04" }
"ui.cursorcolumn.primary" = { bg = "base01" }
"ui.cursorcolumn.secondary" = { bg = "base01" }
"ui.cursorline.primary" = { bg = "base01" }
"ui.cursorline.secondary" = { bg = "base01" }
"ui.debug.active" = { fg = "base09" }
"ui.debug.breakpoint" = { fg = "base08" }
"ui.gutter" = { bg = "base00" }
"ui.gutter.selected" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.highlight" = { bg = "base01" }
"ui.highlight.frameline" = { bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base00" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base06", bg = "base02" }
"ui.picker.header" = { fg = "base04", bg = "base02", modifiers = ["bold"] }
"ui.picker.header.column" = { fg = "base04", bg = "base02" }
"ui.picker.header.column.active" = { fg = "base06", bg = "base02", modifiers = [
  "bold",
] }
"ui.popup" = { bg = "base01" }
"ui.popup.info" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { fg = "base03", bg = "base01" }
"ui.statusline.insert" = { fg = "base0B", bg = "base01" }
"ui.statusline.normal" = { fg = "base04", bg = "base01" }
"ui.statusline.select" = { fg = "base0A", bg = "base01" }
"ui.statusline.separator" = { fg = "base04" }
"ui.text" = { fg = "base05" }
"ui.text.directory" = { fg = "base0D" }
"ui.text.focus" = { fg = "base06" }
"ui.text.inactive" = { fg = "base03" }
"ui.text.info" = { fg = "base05" }
"ui.virtual" = { fg = "base04" }
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.inlay-hint" = { fg = "base03", bg = "base01" }
"ui.virtual.inlay-hint.parameter" = { fg = "base03", bg = "base01" }
"ui.virtual.inlay-hint.type" = { fg = "base03", bg = "base01" }
"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base02" }
"ui.virtual.wrap" = { fg = "base02" }
"ui.window" = { fg = "base02" }

[palette]
base00 = "#151515"
base01 = "#202020"
base02 = "#303030"
base03 = "#505050"
base04 = "#b0b0b0"
base05 = "#d0d0d0"
base06 = "#e0e0e0"
base07 = "#f5f5f5"
base08 = "#cc6666"
base09 = "#de935f"
base0A = "#f0c674"
base0B = "#b5bd68"
base0C = "#8abeb7"
base0D = "#81a2be"
base0E = "#b294bb"
base0F = "#a3685a"
